export default {
  SIGN_UP_SCREEN: 'SignUpScreen',
  SIGN_IN_SCREEN: 'SignInScreen',
  HOME_SCREEN: 'HomeScreen',
  AGENDA_SCREEN: 'AgendaScreen',
  ATTENDEES_SCREEN_TAB: 'AttendeesTabScreen',
  ATTENDEES_SCREEN: 'AttendeesScreen',
  ATTENDEES_DETAILS_SCREEN: 'AttendeesDetailsScreen',
  CHAT_SCREEN: 'ChatScreen',
  CHAT_SCREEN_TAB: 'ChatTabScreen',
  CHAT_SCREEN_DETAILS: 'ChatScreenDetails',
  CHAT_ONE_ON_ONE_SCREEN_DETAILS: 'ChatOneOnOneScreenDetails',
  NEW_CHAT_SCREEN: 'NewChatScreen',
  NOTIFICATION_SCREEN: 'NotificationScreen',
  ONBOARDING_ORGANIC_SCREEN: 'OnboardingOrganicScreen',
  ONBOARDING_MORE_INFO: 'OnboardingMoreInfoScreen',
  ONBOARDING_VERIFY_SCREEN: 'OnboardingVerifyScreen',
  ONBOARDING_PHONENUMBER_SCREEN: 'OnboardingPhoneNumberScreen',
  ONBOARDING_ADDRESS_SCREEN: 'OnboardingAddressScreen',
  ONBOARDING_USERINSYSTEM_SCREEN: 'OnboardingUserInSystemScreen',
  ONBOARDING_INFOREVIEW_SCREEN: 'OnboardingInfoReviewScreen',
  ONBOARDING_EMAIL_SCREEN: 'OnboardingEmailScreen',
  ONBOARDING_NAME_SCREEN: 'OnboardingNameScreen',
  ONBOARDING_PASSWORD_SCREEN: 'OnboardingPasswordScreen',
  WELCOME_IF_USER: 'WelomeIfUser',
  HEY_USER_SCREEN:'HeyUserScreen',
  VERIFY_INFO_IF_USER:'VerifyInfoIfUser',
  ABOUT_SCALE_UP: 'AboutScaleUp',
  ABOUT_SPEAKER_PROFILE: 'AboutSpeakerProfile',
  GLOBAL_LEADERSHIP_PROGRAM: 'GlobalLeadershipProgram',
  RESOURCES: 'Resources',
  EVENT_RESOURCES_EDIT: 'EventResourcesEdit',
  PREPERATION: 'Preperation',
};
